sudo: required
services:
  - docker
language: node_js
install:
  - yarn --ignore-engines
script:
  - yarn run ci
  - yarn danger ci
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
