version: '2.1'

services:
  mongodb:
    extends:
      file: common.yml
      service: mongodb
    volumes:
      - mongostorage:/data/db
    ports:
      - "${MONGODB_EXPOSED_PORT}:27017"

  api:
    extends:
      file: common.yml
      service: api
    ports:
      - "${REST_API_EXPOSED_PORT}:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./:/home/nodejs/app

  tests:
    container_name: tests
    build: .
    volumes:
      - ./:/home/nodejs/app
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/${MONGODB_APPLICATION_DATABASE}"
      TEST_MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/test"
      NODE_ENV: "test"
    depends_on:
      api:
        condition: service_started
    links:
      - api
      - mongodb
    command: npm test

volumes:
  mongostorage: {}
