version: '2.1'
services:
  mongodb:
    container_name: ya-mongo-db
    image: mongo:latest
    volumes:
      - mongostorage:/data/db
    ports:
      - "${MONGODB_EXPOSED_PORT}:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_EXPOSED_PORT=${MONGODB_EXPOSED_PORT}
      - MONGODB_APPLICATION_DATABASE=${MONGODB_APPLICATION_DATABASE}
      # Auth for mongo can be created later with setting up user@password:
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=password
  api:
    container_name: ya-server
    build: .
    restart: always
    mem_limit: 300m
    ports:
      - "${REST_API_EXPOSED_PORT}:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./:/home/nodejs/app
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/${MONGODB_APPLICATION_DATABASE}"
      TEST_MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/test"

  tests:
    container_name: tests
    build: .
    volumes:
      - ./:/home/nodejs/app
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/${MONGODB_APPLICATION_DATABASE}"
      TEST_MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/test"
      NODE_ENV: "test"
    depends_on:
      api:
        condition: service_started
    links:
      - api
      - mongodb
    command: npm test

volumes:
  mongostorage: {}
